# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get SHORT SHA ${SHORT_SHA}
        run: echo "SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Set date
        run: echo "NOW=$(date +'%Y-%m-%d-%H:%M:%S')" >> $GITHUB_ENV

      - name: Build Images
        run: touch test.1 test.2
        
      - name: Release 1 
        uses: ncipollo/release-action@v1
        with:
          tag: mx4300-nss-${{ github.SHA }}
          artifacts: test.1 test.2
        
      - name: Get SHORT SHA 
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Release 2 
        uses: ncipollo/release-action@v1
        with:
          tag: mx4300-nss-"${env.SHORT_SHA}"
          artifacts: test.1 test.2

      - name: Release 3 ${SHORT_SHA}
        uses: ncipollo/release-action@v1
        with:
          tag: mx4300-nss-${SHORT_SHA}
          artifacts: test.1 test.2
